spring:
  servlet:
    # limit upload file size, if the limit is exceeded, MaxUploadSizeExceededException will be thrown
    multipart:
      max-file-size: 2100MB
      max-request-size: 2100MB


logging:
  level:
    root: debug


server:
  port: 8002